import type { PricingRegion } from '@/lib/pricingRegion';

export interface FAQEntry {
  q: string;
  a: string;
}

const costAnswerByRegion: Record<PricingRegion, string> = {
  UK: 'PadiHub has two monthly-only plans. Basic: £4.99/month. Join up to 3 savings groups; cannot create a group. Premium: £14.99/month. Create up to 3 savings groups and join up to 5 more (8 group memberships total).',
  NG: 'PadiHub has two monthly-only plans. Basic: ₦5,000/month. Join up to 3 savings groups; cannot create a group. Premium: ₦10,000/month. Create up to 3 savings groups and join up to 5 more (8 group memberships total).',
};

const contributionFeeAnswerByRegion: Record<PricingRegion, string> = {
  UK: 'A card fee of 1.5% + £0.20 is charged on every contribution, plus an equal share of that cycle\'s payout fee (0.25% of the total pot + £0.20), split across all contributing members and rounded up to the next penny. For example, a £10 contribution in a 5-person group totals £10.42. This surcharge is itemised on-screen before you confirm and is never deducted from the pot.',
  NG: 'A transaction fee of 2% of the contribution plus 7.5% VAT on that fee is charged on every contribution, plus an equal share of that cycle\'s tiered payout fee (₦10 / ₦25 / ₦50 depending on pot size), with VAT shown separately and each share rounded up to the next kobo. This surcharge is itemised on-screen before you confirm and is never deducted from the pot.',
};

// Builds the FAQ list for a resolved region — the "How much does PadiHub
// cost?" answer must show only that region's prices, never both at once.
export function getFaqEntries(region: PricingRegion): FAQEntry[] {
  return [
    { q: 'How do I join a savings group?', a: 'You can join a group by accepting an invitation link from a group leader, or by browsing available groups after you subscribe. Once you request to join, the group leader will approve your membership. A brand-new group only moves from "Draft" to "Active" (and starts collecting contributions) once it has at least 3 verified members.' },
    { q: 'How do I create a savings group?', a: 'After subscribing to a Premium plan, go to My Groups and click "Create Group". Our step-by-step wizard will guide you through setting up your group name, contribution amount, group size, rotation rules and inviting members. The "Start Group" button stays disabled until at least 3 verified members have joined.' },
    { q: 'How do payments work?', a: 'Each cycle (daily, weekly or monthly, depending on your group\'s schedule), every member contributes the agreed amount automatically on the group\'s chosen payout day — there is no manual "make a payment" step. Subscriptions are only charged after successful identity verification. Monthly contributions are subject to processing fees with final group payouts made in full.' },
    { q: 'What time of day are contributions charged and payouts sent?', a: 'On a group\'s payout day, member cards/accounts are charged and that cycle\'s payout is sent starting at 07:00 GMT. An automatic catch-up run at 18:00 GMT the same day retries any accounts that were not yet successfully charged in the morning (for example, due to a brief payment-provider outage) — this catch-up is safe and will never charge you twice for the same contribution.' },
    { q: 'What happens if my group becomes active close to its payout day?', a: 'If a group only reaches 3 active members (or a new member joins) after 17:00 GMT on a date that matches its payout schedule, that day\'s charge and payout are no longer attempted — they automatically move to the same date, or day of the week, in the following week or month. We\'ll show you the updated first contribution and payout dates on the group page.' },
    { q: 'When is my profile fully complete?', a: 'Your profile is fully complete once you have signed up, verified your email, chosen a plan, added and verified your payment card, verified your payout account, and finished identity verification. Joining a savings group comes after that.' },
    { q: 'Why does my account say "Pending Charge"?', a: 'It means you have finished setting up your profile, but you have not yet joined a started group. Your card is checked but not billed until you become part of a group with at least 3 active members. Until then, you can still join or accept invitations up to your plan limit.' },
    { q: 'What if I finish my profile but do not join a group?', a: 'We may send reminder emails about every 7 days while you are waiting to join an active group. If 30 days pass and you still have not joined one, we may move your profile back to incomplete, make your subscription inactive, and ask you to log in, choose a plan again, and join a group before you can become fully active.' },
    { q: 'What if I do not finish setting up my profile?', a: 'Your subscription stays inactive and you cannot join or take part in a group until every setup step is complete. Your dashboard will show what is still missing, and we may send reminder emails about every 7 days. If the profile stays unfinished for 60 days, we may delete the account and email you — you can sign up again later with the same email address.' },
    { q: 'What are the contribution processing fees?', a: contributionFeeAnswerByRegion[region] },
    { q: 'What\'s the grace period for a missed payment?', a: 'If a contribution charge fails, you get a fixed 72-hour grace period before PadiHub automatically retries the charge exactly once. If that single retry also fails, the payment is marked in default. There are no further automatic retries.' },
    { q: 'What happens if someone leaves the group or defaults on a payment?', a: 'Whenever a member leaves (by choice) or is suspended after breaching the group\'s maximum-permitted-defaults setting, that member is removed, the final period on the group\'s timeline is deleted, and everyone remaining moves up one payout slot — this is called Compensated Compression. Recovering a specific missed contribution from a member who later defaults is the group\'s own responsibility, not PadiHub\'s — we\'ll notify everyone clearly, but we do not guarantee, insure, or recover the money for you.' },
    { q: 'Why did my payout date move?', a: 'Your payout date can move if another member leaves or is suspended before your turn — the remaining schedule automatically compresses (Compensated Compression) so nobody waits for a slot that no longer needs filling. We always email every member both the new date and the new payout amount when this happens.' },
    { q: 'Why a contribution fee instead of a payout deduction?', a: 'We add the card/transaction processing fee on top of your contribution, rather than deducting it from the pot, so every recipient still gets their full contribution amount when it\'s their turn to be paid out — nobody\'s payout is ever short-changed by processing costs.' },
    { q: 'How are the first 3 payout slots assigned?', a: 'When a group activates, its first 3 payout slots go to the Group Organiser and/or the members with the highest verified Trust Score at that moment. Anyone admitted to the group after it\'s already running is automatically added to the end of the remaining payout sequence.' },
    { q: 'What happens if the Group Owner leaves the group?', a: 'If the group is still in Draft (fewer than 3 verified members, so nothing has ever been collected), the Owner leaving simply cancels the draft and any members who\'d already joined are notified by email. If the group is already Active, the Owner departs exactly like any other member — the remaining schedule compresses (Compensated Compression) so nobody loses their place — and Owner status automatically transfers to whichever remaining active member has been in the group the longest (earliest join date, based on tenure, not Trust Score). If no other members remain, the group is closed.' },
    { q: 'How long does a savings group run for?', a: 'When creating a group, the Owner chooses whether it runs indefinitely (no end date, until the Owner chooses to close it) or for a fixed number of complete payout rotations (every active member receiving one payout counts as one rotation). A fixed-length group automatically closes once its set number of rotations has completed. An indefinite group can be closed by its Owner at any time from the group page once it isn\'t mid-cycle.' },
    { q: 'Can members vote to remove another member?', a: 'Yes. Any active member can propose a unanimous vote to remove another member for reasons such as repeated missed payments. Every other active member must agree within 48 hours, or the target member stays in the group. As a protection against misuse, a member currently designated as the recipient of the in-progress payout cycle cannot be targeted by a removal vote until after they\'ve received that payout.' },
    { q: 'What happens if I delete my account?', a: 'Your account is deactivated and your personal data is anonymised. We also keep a permanent, hashed record of your email address so it can never be used to create a new PadiHub account — this exists to stop someone from evading a default or suspension history by simply signing up again.' },
    { q: 'What is Trust Score™?', a: 'Trust Score™ is your reputation on PadiHub. It\'s based on your payment history — successful on-time payments and completed cycles increase your score, while missed payments, defaults, or being removed from a group reduce it. A higher Trust Score makes it easier to join new groups and can qualify you for one of the first 3 payout slots.' },
    { q: 'How much does PadiHub cost?', a: costAnswerByRegion[region] },
    { q: 'When does my subscription actually start?', a: 'Your subscription starts on the day you become an active member of a started group with at least 3 active members. It then renews monthly from that date.' },
    { q: 'Can I cancel my subscription?', a: 'Yes, you can cancel anytime from your Settings page. There are no cancellation fees. Your access continues until the end of your current billing period. Note that your subscription billing only ever starts once you\'re a verified member of an active group — it stays inert at signup.' },
    { q: 'What happens if I cancel my subscription?', a: 'Cancelling removes you from any groups you are in and makes your subscription inactive. You will not be able to join groups or receive payouts unless you subscribe again. If you stay inactive, we may send reminder emails, and after 60 days we may delete the account and let you know by email.' },
    { q: 'When does PadiHub send payment failed emails?', a: 'Only in two cases: when your first subscription charge fails after you join an active group, or when a regular group contribution charge fails. We do not send payment failed emails just because your profile is unfinished or your card has not been charged yet.' },
    { q: 'Can I see the other members of my group?', a: 'Yes. In an active group, you can view the other active members from the group page, including their names, join dates, and Trust Score.' },
    { q: 'What happens if I am voted out of a group?', a: 'Each time you are removed from a group, your Trust Score goes down. If you are voted out of groups three times in total, your PadiHub account will be permanently deleted, you will be notified by email, and that email address can never be used to sign up to PadiHub again.' },
    { q: 'How can I reach support?', a: 'Visit our Help Centre at padihub.com/help or contact hello@padihub.com. Support is available Mondays to Saturdays, 9am to 6pm.' },
    { q: 'Is PadiHub secure?', a: 'Yes. PadiHub uses secure payment processing to handle all transactions. We never store your card details. All data is encrypted in transit and at rest.' },
    { q: 'Is PadiHub a bank?', a: 'No. PadiHub is not a bank, wallet or financial institution. We provide the platform and tools that help groups of people save together. We do not hold or manage your funds, and we do not insure or guarantee group contributions, payouts, or losses — that risk sits with the Group Creator and members.' },
  ];
}
