// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const dashboard: { "myGroups": Array<{ "id": string; "name": string; "members": number; "contribution": string; "nextPayment": string; "color": string }>; "notifications": Array<{ "text": string; "type": string; "time": string; "id": string }> };
  export const how_it_works: { "steps": Array<{ "step": string; "title": string; "desc": string; "color": string; "details": Array<string>; "id": string }> };
}
